"""Ingestion pipeline components (PDF extract, sections, chunking, quality, status)."""

from spacebio_evidence_engine.ingestion.chunking import (
    CHUNKING_STRATEGY_VERSION,
    ChunkingPolicy,
    ChunkingResult,
    TextChunk,
    chunk_extraction,
    chunk_sections,
    chunk_text,
    estimate_tokens,
    make_chunk_id,
)
from spacebio_evidence_engine.ingestion.error_reporting import (
    FAILED_INGESTION_STATUS,
    IngestionErrorRecord,
    IngestionFailureStatus,
    IngestionStage,
    InMemoryIngestionErrorStore,
    create_ingestion_error_record,
    redact_error_payload,
)
from spacebio_evidence_engine.ingestion.errors import (
    PDFEmptyError,
    PDFExtractionError,
    PDFOpenError,
)
from spacebio_evidence_engine.ingestion.extract import (
    ExtractedPage,
    ExtractionResult,
    PageOffsetMap,
    extract_pdf_bytes,
    extract_pdf_from_storage,
    extract_pdf_path,
    page_texts,
)
from spacebio_evidence_engine.ingestion.pdf_quality import (
    PDFQualityCategory,
    PDFQualityResult,
    assess_pdf_bytes,
    assess_pdf_path,
    assess_pdf_url,
    score_publication_pdf,
)
from spacebio_evidence_engine.ingestion.reprocess import (
    ReprocessError,
    ReprocessResult,
    ReprocessStrategy,
    UnsupportedReprocessStrategyError,
    reprocess_publication,
)
from spacebio_evidence_engine.ingestion.sections import (
    SectionDetectionResult,
    SectionLabel,
    SectionSpan,
    detect_sections,
    detect_sections_from_text,
)
from spacebio_evidence_engine.ingestion.status import (
    ALLOWED_INGESTION_TRANSITIONS,
    DEFAULT_STATUS_EVENT_LOG,
    IngestionStatus,
    IngestionStatusEventLog,
    IngestionStatusTransition,
    InvalidIngestionStatusTransitionError,
    can_transition_ingestion_status,
    describe_ingestion_status,
    get_ingestion_status,
    parse_ingestion_status,
    transition_ingestion_status,
)

__all__ = [
    "CHUNKING_STRATEGY_VERSION",
    "ChunkingPolicy",
    "ChunkingResult",
    "ExtractedPage",
    "ExtractionResult",
    "ALLOWED_INGESTION_TRANSITIONS",
    "DEFAULT_STATUS_EVENT_LOG",
    "FAILED_INGESTION_STATUS",
    "InMemoryIngestionErrorStore",
    "IngestionErrorRecord",
    "IngestionFailureStatus",
    "IngestionStage",
    "IngestionStatus",
    "IngestionStatusEventLog",
    "IngestionStatusTransition",
    "InvalidIngestionStatusTransitionError",
    "PageOffsetMap",
    "PDFEmptyError",
    "PDFExtractionError",
    "PDFOpenError",
    "PDFQualityCategory",
    "PDFQualityResult",
    "SectionDetectionResult",
    "SectionLabel",
    "SectionSpan",
    "TextChunk",
    "assess_pdf_bytes",
    "assess_pdf_path",
    "assess_pdf_url",
    "can_transition_ingestion_status",
    "chunk_extraction",
    "chunk_sections",
    "chunk_text",
    "create_ingestion_error_record",
    "describe_ingestion_status",
    "detect_sections",
    "detect_sections_from_text",
    "estimate_tokens",
    "extract_pdf_bytes",
    "extract_pdf_from_storage",
    "extract_pdf_path",
    "get_ingestion_status",
    "make_chunk_id",
    "page_texts",
    "parse_ingestion_status",
    "redact_error_payload",
    "ReprocessError",
    "ReprocessResult",
    "ReprocessStrategy",
    "reprocess_publication",
    "score_publication_pdf",
    "transition_ingestion_status",
    "UnsupportedReprocessStrategyError",
]
