"""Ingestion pipeline components (PDF extract, section detection, chunking, quality)."""

from spacebio_evidence_engine.ingestion.chunking import (
    CHUNKING_STRATEGY_VERSION,
    ChunkingPolicy,
    ChunkingResult,
    TextChunk,
    chunk_extraction,
    chunk_sections,
    chunk_text,
    estimate_tokens,
    make_chunk_id,
)
from spacebio_evidence_engine.ingestion.error_reporting import (
    FAILED_INGESTION_STATUS,
    IngestionErrorRecord,
    IngestionFailureStatus,
    IngestionStage,
    InMemoryIngestionErrorStore,
    create_ingestion_error_record,
    redact_error_payload,
)
from spacebio_evidence_engine.ingestion.errors import (
    PDFEmptyError,
    PDFExtractionError,
    PDFOpenError,
)
from spacebio_evidence_engine.ingestion.extract import (
    ExtractedPage,
    ExtractionResult,
    PageOffsetMap,
    extract_pdf_bytes,
    extract_pdf_from_storage,
    extract_pdf_path,
    page_texts,
)
from spacebio_evidence_engine.ingestion.pdf_quality import (
    PDFQualityCategory,
    PDFQualityResult,
    assess_pdf_bytes,
    assess_pdf_path,
    assess_pdf_url,
    score_publication_pdf,
)
from spacebio_evidence_engine.ingestion.sections import (
    SectionDetectionResult,
    SectionLabel,
    SectionSpan,
    detect_sections,
    detect_sections_from_text,
)

__all__ = [
    "CHUNKING_STRATEGY_VERSION",
    "ChunkingPolicy",
    "ChunkingResult",
    "ExtractedPage",
    "ExtractionResult",
    "FAILED_INGESTION_STATUS",
    "InMemoryIngestionErrorStore",
    "IngestionErrorRecord",
    "IngestionFailureStatus",
    "IngestionStage",
    "PageOffsetMap",
    "PDFEmptyError",
    "PDFExtractionError",
    "PDFOpenError",
    "PDFQualityCategory",
    "PDFQualityResult",
    "SectionDetectionResult",
    "SectionLabel",
    "SectionSpan",
    "TextChunk",
    "assess_pdf_bytes",
    "assess_pdf_path",
    "assess_pdf_url",
    "chunk_extraction",
    "chunk_sections",
    "chunk_text",
    "create_ingestion_error_record",
    "detect_sections",
    "detect_sections_from_text",
    "estimate_tokens",
    "extract_pdf_bytes",
    "extract_pdf_from_storage",
    "extract_pdf_path",
    "make_chunk_id",
    "page_texts",
    "redact_error_payload",
    "score_publication_pdf",
]
