"""PostgreSQL full-text search column type helpers (issue #45).

Production uses ``tsvector``; SQLite CI uses a nullable text stand-in.
"""

from __future__ import annotations

from typing import Any

from sqlalchemy import Text
from sqlalchemy.types import TypeDecorator


class FullTextSearchVector(TypeDecorator):
    """Store ``tsvector`` on PostgreSQL and plain ``text`` on SQLite.

    The actual ``tsvector`` value is generated by the database from
    ``chunk_text``; the ORM rarely reads it. SQLite uses ``text`` so
    Alembic ``upgrade head`` stays runnable in fast CI migration tests.
    """

    impl = Text
    cache_ok = True

    def load_dialect_impl(self, dialect: Any) -> Any:
        if dialect.name == "postgresql":
            from sqlalchemy.dialects.postgresql import TSVECTOR

            return dialect.type_descriptor(TSVECTOR())
        return dialect.type_descriptor(Text())
